// Generated by github.com/adamluo159/cellnetEx/protoc-gen-msg
// DO NOT EDIT!
// Source: pb.proto

package test

import (
	"github.com/adamluo159/cellnetEx"
	"reflect"
	_ "github.com/adamluo159/cellnetEx/codec/gogopb"
	"github.com/adamluo159/cellnetEx/codec"
)

func init() {

	// pb.proto
	cellnetEx.RegisterMessageMeta(&cellnetEx.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*ContentACK)(nil)).Elem(),
		ID:    60952,
	})
}
